microsoft/vscode-arduino

.vscode/launch.json, .vscode/tasks.json, README.md, gulpfile.js, package.json, src/arduino/arduinoContentProvider.ts, src/arduino/vscodeSettings.ts, src/views/app/components/BoardManager.tsx, src/views/app/components/LibraryManager.tsx, src/views/app/styles/board.scss
@testforstephen @akaroml @andxu
=> Make package/library update as a manual operation

package.json, src/arduino/vscodeSettings.ts, src/serialmonitor/usbDetector.ts
See issue #389  Provider the customer alternative options. Default behavior is not changed. 
@andxu @testforstephen  @akaroml
=> Add settings for enable/disable USB detection.

CHANGELOG.md, README.md
=> Update change log.

src/arduino/boardManager.ts
@testforstephen @andxu @akaroml
=> Add defensive code.

src/arduino/arduino.ts, src/common/outputChannel.ts, syntaxes/arduino.output.tmLanguage
=> Refine the output message.

package-lock.json, src/serialmonitor/serialMonitor.ts
@testforstephen @andxu @akaroml
=> Change defautl baud rate.

.travis.yml, package-lock.json, src/views/package-lock.json
=> Fix down package.json version.

package.json
=> Update package.json version.

.travis.yml
The latest VSCode (1.21) has permission issue on Ubuntu, use 1.20.1 on Travis for test
=>  Use vscode 1.20.1 in Linux for Travis

src/common/constants.ts
Related issue: https://github.com/Microsoft/vscode-arduino/issues/483
=> fix status bar item conflict with c/c++ extension priority

src/arduino/arduino.ts
Related issue: https://github.com/Microsoft/vscode-arduino/issues/450
=> support absolute path for build output

src/arduino/boardManager.ts
Related issue: https://github.com/Microsoft/vscode-arduino/issues/414
=> Do not union boards

src/arduino/arduino.ts, src/extension.ts
=> add cStandard and cppStandard, auto update package list for install board api

src/arduinoActivator.ts, src/common/constants.ts, src/deviceContext.ts, src/extension.ts, test/extension.test.ts
=>  add change sketch config

package.json, src/arduino/vscodeSettings.ts, src/serialmonitor/usbDetector.ts
related issue: https://github.com/Microsoft/vscode-arduino/issues/495
=> add ignore board

README.md
IoT Developer Blog Space link update
=> IoT Developer Blog Space link update

CHANGELOG.md, package-lock.json, package.json
Updated version and change logs.
=> Pre release v0.3.1

CHANGELOG.md, package-lock.json, package.json
=> Release prepare

CHANGELOG.md, package-lock.json, package.json
update version and change log.
=> Pre release v0.3.2

src/serialmonitor/serialportctrl.ts
Adds DTR signal to reset board when serial monitor is opened or the buad rate is changed.
=> Serial fix

.github/workflows/build.yml
Update build to run on new dev branch
=> Change build to dev branch

src/serialmonitor/serialportctrl.ts
=> fix send serial message

src/arduino/arduino.ts
=> Fix build cwd (#1374)

package.json
Based on discussion from #1481
=> Scope activation to only *.ino files

src/arduino/arduino.ts
Addresses comments from #1490.
=> Add additional verbose output regex

build/build.yml, build/prerelease.yml, build/tsa.gdntsa
Real signing was enabled faster than I expected.
=> Real sign pre-release builds
