microsoft/vscode-arduino

package.json
src/common/util.ts

sorry about my poor English first..... m(_ _)m
When I use vscode-arduino at Chinese Windows system, output encoding is broken.
because Windows non-unicode app return by ansi.
so we can get ansi codepage, and use iconv-lite to decode it to utf8.

win32 platform support not utf8 encoding at childProcess.spawn() stdout/stderr

---

src/arduino/arduinoSettings.ts
src/common/sys/darwin.ts
src/common/util.ts

On Mac Arduino app has to be called "Arduino.app". In some cases (include me) we add a version number to keep a bunch of Arduino due to compatibility issues.
This PR add a regex check when generating a path. If it already specify a Arduino app, no "Arduino.app" is added.

Add more freedom on Mac with different version of Arduino

---

misc/usbmapping.json

This is an addition for debugging STM32F1 series with
https://github.com/rogerclarkmelbourne/Arduino_STM32
Tested with $2 STM32F103C8T6 "blue pill" board and $2 ST link V2
Also tested with GD32F103C8T6

Add board support for STM32F1 with Arduino_STM32

---

src/arduino/arduino.ts
src/extension.ts
src/serialmonitor/usbDetector.ts

Pause UsbDetector during uploading, so that the resetting of board during uploading will not trigger an annoying display of the board's README.

Pause UsbDetector during uploading

---

src/arduino/arduino.ts

According to https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md#what-is-the-difference-between-includepath-and-browsepath-in-c_cpp_propertiesjson
> it is still important to ensure that the browse.path setting is properly set.
So browse.path is needed to be updated when including library, too.

Update browse.path when include library

---

README.md
src/arduino/arduino.ts

- Fix the problem that upload ignores the output path config, which leads to long upload time (The whole sketch is verified before each upload).
- Add warning about missing output path config, which may cause long upload/verify time.
- Add document for `arduino.json` in README

Leverage the output path config to speedup upload/verify

---

src/extension.ts
src/serialmonitor/usbDetector.ts

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
fix issue: https://github.com/Microsoft/vscode-arduino/issues/430

pop up the example web view when detecting a new iot device to be connected

---

package.json
src/arduinoContext.ts
src/debug/configurationProvider.ts
src/extension.ts
test/extension.test.ts

@andxu @testforstephen @akaroml

Adopt the new VSCode Debug API.

---

package.json
src/debug/configurationProvider.ts

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

Fix variable reference bug in package.json for new vscode engine

---

README.md
package.json
src/arduino/arduinoSettings.ts
src/arduino/vscodeSettings.ts

This change introduces a new workspace setting called `commandPath`.
Through this setting a user can specify a custom Arduino launch wrapper or script.
This is useful for example on macOS, to remove the default behaviour of showing the Arduino splash screen during sketch builds. To achieve this, one would create a launch script as described here: https://github.com/arduino/Arduino/issues/1970#issuecomment-321975809
Using the new `commandPath` setting, the user would instruct the vscode Arduino extension to invoke Arduino via this script, rather then the default binary.
When this setting is not configured or is an empty string value, the default Arduino binary is used as previously.
Default behavior is not changed. 
@andxu @testforstephen @akaroml

New setting - commandPath - custom arduino launch script

---

src/deviceContext.ts

added logic for populating required Arduino.json properties when findfiles request is rejected

Workaround for internal change with workspace.findfiles

---

src/arduino/arduinoSettings.ts

Related issue: https://github.com/Microsoft/vscode-arduino/issues/415

support portable package

---

src/common/constants.ts
src/extension.ts
src/serialmonitor/serialMonitor.ts
src/serialmonitor/serialportctrl.ts
test/extension.test.ts
vendor/node-usb-native/lib/serialport.js

Related issue: https://github.com/Microsoft/vscode-arduino/issues/497

Add line ending for serial port

---

src/arduino/arduinoSettings.ts

Related issue: https://github.com/Microsoft/vscode-arduino/issues/415

fix example issue for protable mode

---

src/arduino/boardManager.ts

related issue: https://github.com/Microsoft/vscode-arduino/issues/520

fix board version issue

---

src/arduino/arduino.ts

Related issue: https://github.com/Microsoft/vscode-arduino/issues/438
This is not the final solution.
We still have some work to do...
intelliSense works in the most time with this fix, however, I have to include Arduino.h in the built in example, or built in functions are marked as undefined:
Then I include Arduino.h manually, intelliSense works:
BUT, as you can see, there is still a warning message in include section - some header file required by Arduino.h is not found in include path of c_cpp_properties.json.
Include path is not recursive currently. And it is also not possible to add all header files into c_cpp_properties.json. So what we can do on fixing this error is very limited.
intelliSense should just work now, except for include part...

First try to fix intelliSense issue

---

src/extension.ts

add progress status for verify and upload

---

README.md
src/arduino/arduino.ts
src/deviceContext.ts

add prebuild for build and verify

---

README.md
package.json
src/arduino/vscodeSettings.ts
src/langService/completionProvider.ts

With the VsCode C++ extension 0.17, it now automatically handles #include providers when properly set up.
This shouldn't be completely removed from this extension as there are still some use cases, but this adds a way to disable the arduino extensions provider if the user wants to.

Adds way to skip header file provider

---

src/extension.ts

Fixed typo for "verifying" in status bar

---

src/arduino/arduino.ts

hello, with commit #653 the output path not existing issue was fixed by @czgtest 
he did it for upload and verify but the arduino IDE so vscode have also another method of upload "upload with programmer" 
in this pull request i didn't did nothing special, i just copy-paste the good fix of czgtest to the other upload method

apply commit #653 also to upload using programmer

---

README.md

Fixed major grammatical issues & formatting issues

---

misc/debuggerUsbMapping.json
misc/usbmapping.json

There is an opensource [debugWIRE implementation](https://github.com/dcwbrown/dwire-debug) that can debug Arduino Uno.
By adding config into the 2 json files, VScode will be capable to debug Arduino Uno. 
Here is an instruction https://github.com/DeqingSun/Debugging-Arduino-Uno

add debugging support for uno

---

misc/usbmapping.json

The board is distributed by SORACOM only.
https://soracom.jp/products/module/wio_lte_m1_nb1/
Verify result:

Add Wio LTE M1/NB1(BG96) board

---

CONTRIBUTING.md

added a contribution guidelines similar to contribution guideline found on other vscode related repositories.

added contribution guidelines

---

src/arduino/exampleManager.ts

solves #652 
video:
https://streamable.com/llhuc
@czgtest also said it would be a nice feature

add sketch folder to examples

---

.travis.yml
package-lock.json
package.json
src/extension.ts
src/serialmonitor/usbDetector.ts

https://github.com/Microsoft/vscode-arduino/issues/701

use webview api instead of preview html

---

README.md

Please, update the readme for Mac users

Added port example for Mac Users.

---

package-lock.json
package.json
src/extension.ts
src/views/package-lock.json

`.pde` will be remaned to `.ino` automatically. https://github.com/Microsoft/vscode-arduino/issues/752

add .pde support

---

README.md
package.json
src/arduino/vscodeSettings.ts
src/extension.ts

referencing issue #838 
This is really an annoying issue with these asking FOR pde support:
#217 #752 #793 
but they are all individually wrong:
PDE is for processing, arduino uses INO. Arduino DID use pde _prior to the first release_ ( as it was a cut-copy of Processing ) but now PDE on arduino is considered "read only" - [read more here](https://www.arduino.cc/en/guide/environment)
Now with Ardiuno on 1.8.9 and Processing on 3.5.3; Both popular, both being used in their own way, allowing people to use pde files for arduino is sacrilegious to both camps.
In regards to other arduino-based examples and etc using PDE. (Looking at #752 specifically ) The correct place to submit an issue is on THAT codebase to rename .pde; not for tools like this one to support pde. 
It also makes life …

Remove Processing Filetype (.PDE extension)

---

src/arduino/arduino.ts
src/common/util.ts

See #869 
When the path on a Windows machine is broken in such a way that chcp cannot be successfully invoked, an error occurs and the returned reason object does not have a code property as expected by the error handler. This results in the unhelpful error message `code=undefined`
There are two problems here: 
* defective error handling
* weak handling of a scenario for which there is a reasonable default
The catch clause checks whether `code` or `message` properties are present and falls back to stringifying the whole object.
The code page is 850 for the English speaking world. When a value cannot be obtained and the default is used a warning is generated that includes the error message returned from the attempt to invoke chcp.

Windows codepage bugfix

---

src/arduino/arduino.ts

When running with a portable version of Adruino IDE, the custom libraries are put in: 
--> arduino-1.8.10\portable\sketchbook\libraries
(and not in Documents\Arduino\libraries).
This PR replaces the hard coded ref to Documents\Arduino\libraries with a ref to _settings.sketchbookPath that works with the portable version and the installed one.

Support custom libraries with portable version of Arduino

---

.travis.yml
package-lock.json
package.json
src/serialmonitor/serialportctrl.ts
src/serialmonitor/usbDetector.ts

1. fix bug: showing device readme file will crash
1. update travis ci for usb-native

fix usb-detection bug and update travis ci script

---

.travis.yml
CONTRIBUTING.md
README.md
test/extension.test.ts

1. Add windows environment to Travis CI.
2. Fix test error for stopping usb detector on windows.
3. Update Contribution guide to tell the code fix flow which is working against develop branch not master branch.
4. Update Readme to remove recommended Arduino IDE version since version 1.8.8 is out of date.

add windows for travis ci

---

src/serialmonitor/usbDetector.ts

Fix:
Setting up or switching board config requires `arduino.json` file, and will create it if not exist. But the file is not needed for non-arduino project. 
Update the case to only when it is Arduino project or "*.ino" file actively opened which is the same criteria as Arduino extension activated, usb detector will set up board config and open Arduino examples.

update usb detector

---

package-lock.json
package.json
src/logger/logger.ts
src/logger/telemetry-transport.ts
src/logger/user-notification-transport.ts

1.update dependency "vscode-extension-telemetry" to version 0.1.6
2. set firstParty = true for TelemetryReporter.
3. use sendTelemetryErrorEvent to suppress sending telemetry of error details.
4. update name of telemetry with error from "error" to predefined message.

suppress sending telemetry of error details

---

src/serialmonitor/serialportctrl.ts

fix: https://github.com/microsoft/vscode-arduino/issues/1015
Root cause: the serialport lib we used causes the issue, see [serialport issue](https://github.com/serialport/node-serialport/issues/1854) and [hupcl](https://github.com/serialport/node-serialport/issues/1678). 
workaround: [link](https://github.com/serialport/node-serialport/issues/1854#issuecomment-496887057).

fix: serial monitor keeps esp devices in flash mode

---

CHANGELOG.md
package-lock.json
package.json

Merge release v0.3.1 to develop branch

Merge release v0.3.1 to develop branch

---

gulpfile.js
package-lock.json
package.json
src/views/package-lock.json
src/views/package.json
test/index.ts
test/runTest.ts
tslint.json

1. Migrate vscode to vscode-test for unit tests.
2. Update version of webpack, eslint, node-sass.
3. Add dependency of acorn to fix npm warning "acorn-jsx@5.2.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed" after upgrading eslint version.

fix security vulnerabilities

---

src/arduino/arduino.ts

This is a pretty heavy handed approach, but it seems to work decently well.

Quick fix for Intellisense

---

package.json
src/arduino/arduino.ts
src/arduino/arduinoSettings.ts
src/arduino/programmerManager.ts
src/arduino/vscodeSettings.ts
src/common/platform.ts
src/common/sys/darwin.ts
src/common/sys/linux.ts
src/common/sys/win32.ts
src/common/util.ts
src/extension.ts
test/extension.test.ts
test/librarymanager.test.ts

Solves the issue #856 
* Adds a checkbox to the configuration interface to choose between standard Arduino and the CLI version ;
* Is necessary to explicitly set "arduino-cli" in command path;
* the support for Windows and MacOS is not complete.

Option to use arduino-cli instead of Arduino IDE

---

CHANGELOG.md
package-lock.json
package.json
src/arduino/arduino.ts
src/arduino/arduinoSettings.ts
src/arduino/programmerManager.ts
src/arduino/vscodeSettings.ts
src/common/platform.ts
src/common/sys/darwin.ts
src/common/sys/linux.ts
src/common/sys/win32.ts
src/common/util.ts
src/deviceContext.ts
src/extension.ts
src/serialmonitor/serialMonitor.ts
src/serialmonitor/serialportctrl.ts
test/extension.test.ts
test/librarymanager.test.ts

- Selected programmer is now saved to and loaded from the arduino.json file
- Arduino.json is monitored for changes, and changing file will update selected programmer & ui
- Programmer selection UI now shows both the friendly name of the programmer, as well as the arduino name
- Minor fix to deviceContexts to fire change events after all states are modified
- Layed groundwork to support querying list of programmers for the current board from arduino toolchain
Fixes #942

Improved handling of programmer selection

---

src/arduino/intellisense.ts

```-MMD``` complier arg creates a file named null.d in the workspace directory. This PR removed the argument from intelliSense configuration.
Resolves #1206

remove -MMD from complier args for intellisesne

---

src/views/app/components/BoardConfig.tsx
src/views/app/components/BoardManager.tsx
src/views/app/components/ExampleTreeView.tsx
src/views/app/components/LibraryManager.tsx

This project is still running on react 15, and these `UNSAFE_*`-lifecycle aliases where not introduced until 16.3, hence they are never called.
fixes #1163, fixes #1360, fixes #1363, fixes #1361, fixes #1372

Fix empty board and examples list

---

.eslintrc.yml
src/arduino/arduino.ts
src/arduino/intellisense.ts
src/arduino/package.ts
src/common/constants.ts
src/logger/logger.ts

Eslint will requires a typescript specialized version of the no-unused-vars rule in order to properly understand the use of enums.

Fix eslint parsing for enums

---

.github/workflows/build.yml
azure-pipelines.yml
build/checkHash.js

Because the ADO pipeline now handles creation of a GH release, we can simplify the GH actions to just provide quick build and test feedback across all platforms. It's worth keeping this on GH so that external contributors can inspect the build logs, which is impossible with ADO (by design).

 Remove deploy and add Windows test to GH actions

---

src/arduino/arduino.ts

I realize this implementation may not be the best, but it should work fine. 
You can implement a better solution when you'll have time, meanwhile many people need this fixed now.

Fix #1215 Output sketch memory usage in non-verbose mode

---

src/arduino/boardManager.ts
src/common/sharedUtilities/utils.ts
src/deviceContext.ts
src/views/app/components/BoardItemView.tsx
src/views/app/components/BoardManager.tsx
src/views/app/components/LibraryItemView.tsx
src/views/app/components/LibraryManager.tsx
src/views/app/reducers/boardManagerReducer.ts
src/views/app/reducers/libraryManagerReducer.ts
src/views/app/utils/util.ts
src/views/tsconfig.json

Show all supported boards and set default build directory

---

.github/workflows/build.yml
README.md
package.json
src/arduino/arduinoSettings.ts
src/arduino/vscodeSettings.ts
src/common/constants.ts
src/extension.ts
src/serialmonitor/serialMonitor.ts
src/serialmonitor/serialportctrl.ts
test/extension.test.ts

Now you can print timestamp before each line of Serial Monitor output.
Format of timestamp can be changed using command "Arduino: Change Timestamp Format" (`arduino.changeTimestampFormat`).
You can find list of all available placeholders here: https://strftime.org.
---
Example ("Timestamp Format" set to `%H:%M:%S.%f -> `):
```
[Starting] Opening the serial port - /dev/cu.usbmodemFA131
17:13:18.016370 -> 0
17:13:19.019009 -> 1
17:13:20.018564 -> 2
17:13:21.018022 -> 3
17:13:22.017378 -> 4
17:13:23.020687 -> 5
...
```
---
This PR adresses these issues:
- https://github.com/microsoft/vscode-arduino/issues/936
- https://github.com/microsoft/vscode-arduino/issues/1088
- https://github.com/microsoft/vscode-arduino/issues/1214
**Warning!** This PR depends on …

Add option for printing timestamp before each line of Serial Monitor output

---

src/serialmonitor/serialportctrl.ts

Implementation of https://github.com/microsoft/serial-monitor-cli/pull/11 into extension.
---
This PR adresses this issue:
- https://github.com/microsoft/vscode-arduino/issues/1362
**Warning!** This PR depends on https://github.com/microsoft/serial-monitor-cli/pull/11
---
@benmcmorran or @gcampbell-msft, please, could you review?

Fix problem with stripping whitespace

---

azure-pipelines.yml
build/markExecutableFiles.py
src/serialmonitor/serialportctrl.ts

This is follow-up from a change in the serial-monitor-cli repo to add extensions to the Linux and Mac serial monitor executables.

Re-enable VSIX signing

---

README.md

Corrected some keyboard shortcuts for when the user developing using a Mac

Added Mac shortcuts on readme

---

.github/workflows/build.yml
CONTRIBUTING.md
README.md
azure-pipelines.yml
package.json

Historically this repo had a separate branch for production releases, which was integrated with the main branch before and after releases. This seems needlessly complex, especially because VS Code follows the Modern Lifecycle Policy, so we don't need to service old versions of the extension.
This PR removes references to the `release` branch. Going forward, we will directly tag production releases from `main`, which matches the approach used by other Microsoft VS Code extensions. Once this PR merges, I'll update the wiki with documentation on the new release process.

Use main branch for production releases

---

.vscode/settings.json

When trying to execute the "Launch Extension" launch task on my Raspberry Pi running Raspberry Pi OS 64 bit while accessing the `microsoft/vscode-arduino` repository on my Raspberry Pi remotely, gulp is not able to be found despite being installed on my machine. I had originally tested running the shell in interactive mode, and this seemed to fix the issue, but I was worried about this fix not working on other shells. Additionally, causing the shell to default to bash despite user OS settings did not seem like an appropriate fix.
This change loads the user settings into the default Linux terminal, ensuring that packages installed using `npm i -g` are available via the user's path setting. Additionally, this should help `nvm` load the version of `node` specified by the user instead of …

Fix Launch Extension gulp Not Found on Linux

---

src/arduino/arduinoContentProvider.ts
src/arduino/localWebServer.ts

Currently, the port of the workspace extension on the remote host is not automatically forwarded in the local VS Code instance. This PR uses `vscode.env.asExternalUri` in `arduinoContentProvider` instead of `localhost`, so the port is automatically forwarded. This way, calls to the API don't fail from the local UI. To isolate the issue, I opened up the dev tools for VS Code and manually forwarded the port the Arduino extension was using for the web server. The board view showed up after forwarding, indicating it is not automatically forwarded.
[Microsoft Docs Reference](https://code.visualstudio.com/api/advanced-topics/remote-extensions#forwarding-localhost)
Fixes #1064 
- VS Code: 1.64.2
- Arduino v0.4.11 (Installed from Extension Marketplace)
- VS Code: 1.64.2
- No Arduino Extension …

Support Remote Development Board Selection

---

README.md
package.json

This project recently moved (in https://github.com/microsoft/vscode-arduino/pull/1450) to a different serial port library that uses another library for the time handling than the previous one.
There are different placeholders for time specifiers, so I updated the link to the list of all available placeholders to the correct website.
> https://strftime.org –> https://github.com/samsonjs/strftime#supported-specifiers
---
This PR addresses this issue:
- https://github.com/microsoft/vscode-arduino/issues/1469
---
@benmcmorran or @gcampbell-msft, would you mind reviewing?

Change link to list of all available placeholders

---

src/serialmonitor/serialportctrl.ts

This should avoid issues with accidentally resetting boards or putting them into download mode, like #1458 and maybe #1467.

Keep DTR, CTS, and RTS high

---

README.md
package.json
src/arduino/arduino.ts
src/arduino/arduinoSettings.ts
src/arduino/vscodeSettings.ts
src/arduinoActivator.ts

This addresses comments from #1287.

Add analyzeOnOpen and analyzeOnSettingChange

---

package.json
test/commands.test.ts

Using the `*` activation event is not a best practise. Instead, it should use `onLanguage:cpp` or something similar.
I realized that in `onCommand:arduiono.cliUploadUsingProgrammer` is a typo so that's also fixed in this PR...
---
Related to
- https://github.com/microsoft/vscode-arduino/issues/1478

Don't use `*` activation event

---

src/arduino/arduino.ts

stdoutcb/stderrcb assume that an input string is a single line, but in fact it can contain multiple lines, or even be a part of a line.
One of the consequence is that cocopa fails to parse compiler output when it contains long lines (#1275).
This patch fixes the issue by introducing a buffer to accumulate received data before passing them to callbacks.
Fixes #1275.

Fix line-oriented callbacks

---

package-lock.json
webpack.config.js

This is a workaround to make sure the web-packing happens correctly so that the extension can be functional. 
The items added to the "unbundledModule" are packages that are used from the node-serialport package, and this ensures that they are included and not bundled. 
I have created a package locally using 'vsce package' in order to create a vsix and tested that the commands seem to work. I didn't test each command end to end, but commands exist and are able to be called.

Add items to the unbundled module to fix webpacking

---

src/views/app/components/LibraryManager.tsx

ReactList may call itemRenderer with an index larger than list length when the component is being updated. Failing to handle the case causes the rendering to break due to an unhandled exception.
For example, try searching for "audioq". Until one types "audio", search results are correctly narrowed, but typing the final letter "q" does not update the results to zero due to an unhandled exception.
This patch fixes the issue by handling out of band indices in itemRenderer.
Fixes #1109

Fix library search result rendering

---

src/arduino/boardManager.ts

This PR fixes `Board Manager` showing less vesions than expected. It happens because platform name may change between releases and there's a condtion which skips any other than the first one added. To keep the same behaviour as Arduino IDE it will always keep the latest platform name as source of truth.
Fixes #1511

Fix incorrect loaded boards when platform name changes

---

README.md

As documented in issue #1477 Version 2 of the IDE isn't supported, so updating the README to make this explicit.

Document that Arduino IDE 2.X is not supported

---

test/librarymanager.test.ts
test/programmermanager.test.ts

AzureIoTHub was [removed from the official list of libraries shown in Arduino's Library Manager](https://github.com/arduino/library-registry/pull/1640/files) on August 3, 2022, and this extension's automated tests have been failing since then. This PR switches to testing against FastLED instead, a popular third-party library that's unlikely to vanish anytime soon.

Remove deprecated AzureIoTHub library from tests

---

gulpfile.js
package-lock.json
package.json
src/logger/telemetry-transport.ts
src/views/package-lock.json
webpack.config.js

This uses the same telemetry pipeline as all other first-party C++ VS Code extensions. I tried firing some new events and will follow-up before merging to ensure they were successfully ingested.

Send telemetry to usual VS Code extension pipeline

---

.github/workflows/build.yml
.vscodeignore
assets/platform/alpine-arm64/placeholder.txt
assets/platform/alpine-x64/placeholder.txt
assets/platform/darwin-arm64/placeholder.txt
assets/platform/darwin-x64/placeholder.txt
assets/platform/linux-arm64/placeholder.txt
assets/platform/linux-armhf/placeholder.txt
assets/platform/linux-x64/placeholder.txt
assets/platform/win32-arm64/placeholder.txt
assets/platform/win32-ia32/placeholder.txt
assets/platform/win32-x64/placeholder.txt
azure-pipelines.yml
build/SignFiles.proj
build/SignVsix.proj
build/package.js
package.json

This will set us up to bundle platform specific copies of `arduinio-cli` with the extension. I tried pushing [a test tag](https://github.com/microsoft/vscode-arduino/releases/tag/platform-specific-release-pipeline-test) to verify the GitHub publishing steps, and everything seems to work correctly, including signing and installation in VS Code.

Add platform-specific VSIX publishing

---

src/arduino/arduino.ts
src/common/util.ts

Fixes a few issues when using Arduino CLI:
- Arduino CLI seems to always use LF newlines regardless of the operating system. We were looking for CRLF on Windows (Arduino IDE behavior) which meant the compile output parser never got any data.
- The Arduino CLI process can exit before all the output data has been received on stdout by VS Code. The data arrives quickly but we need to use the `close` event on the child process to be sure we don't start parsing until the streams are closed.
- (cosmetic) By default, Arduino CLI uses terminal escape sequences to color certain parts of the output. These look ugly in VS Code's output window, which is not a terminal emulator. Pass the `--no-color` option to leave them out, at least for compile. We likely need to pass this flag in other places as …

Fix IntelliSense configuration for Arduino CLI

---

CHANGELOG.md
src/arduino/arduinoContentProvider.ts
src/views/app/actions/api.ts
src/views/app/components/BoardConfig.tsx

Found this usability issue when testing the bundled Arduino CLI on a fresh machine. When the user first tries to verify or upload, an error will appear say that a board needs to be selected. However, when the statusbar item is clicked to select a board, the dropdown is empty. This is because Arduino CLI has no boards installed by default. This PR adds a link to the Boards Manager in this case so that the user can install the board package they need.

Show warning when no boards are installed

---

src/serialmonitor/serialMonitor.ts

Fix the output message when trying to open a serial monitor that isn't plugged in.
Error: 
Fixed:

fix the error message to output the message, not the object

---

CHANGELOG.md
package-lock.json
package.json
src/arduino/exampleProvider.ts
src/views/app/components/ExampleTreeView.tsx

Add warning and link for no installed examples

---

src/arduino/arduinoSettings.ts
src/common/constants.ts

Don't set CLI executable bit if already set

---

CHANGELOG.md
build/assets.json
cgmanifest.json

Arduino CLI 0.31.0 was released earlier today.

Update bundled Arduino CLI to 0.31.0

---

build/build.yml

These tasks are currently issuing deprecation warnings in the build.

Update task versions

---

CHANGELOG.md
src/arduino/arduino.ts
src/arduino/boardManager.ts

Previously, refreshing the board index or library index simply attempted to install a board or library named "dummy", which doesn't make any sense in the Arduino CLI. Additional URLs from `arduino.additionalUrls` were also only written to a settings file but not passed to the Arduino CLI, so it was difficult to install third party boards or libraries.
This PR changes that behavior to call `core update-index` or `lib update-index` as appropriate, and wraps calls to the CLI to always pass the `--additional-urls` flag.

Fix board and library updates for CLI

---

src/serialmonitor/serialMonitor.ts

The goal of this PR is to output helpful error information for commands that need the Serial Monitor API. It should let the user know if the Serial Monitor API is undefined, which could be due to an old version of the Serial Monitor extension.

Add helpful error messages related to serial monitor api
